// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"context"
	"example/bootstrap"
	"example/internal/client"
	"example/internal/helper"
	"example/internal/input/application/command"
	authentication4 "example/internal/input/application/command/admin/authentication"
	command2 "example/internal/input/application/command/admin/resource"
	"example/internal/input/application/consumer"
	consumer2 "example/internal/input/application/consumer/admin/resource"
	"example/internal/input/application/cron"
	authentication2 "example/internal/input/application/cron/admin/authentication"
	cron2 "example/internal/input/application/cron/admin/resource"
	"example/internal/input/application/daemon"
	source2 "example/internal/input/application/daemon/watcher/source"
	"example/internal/input/application/facade"
	"example/internal/input/application/facade/admin/authentication"
	facade3 "example/internal/input/application/facade/register"
	facade2 "example/internal/input/application/facade/table"
	"example/internal/input/application/http"
	"example/internal/input/application/http/admin/authentication"
	resource2 "example/internal/input/application/resource"
	"example/internal/input/application/resource/model"
	resource3 "example/internal/input/application/source"
	"example/internal/input/application/source/announcement"
	"example/internal/input/application/tcp"
	authentication5 "example/internal/input/application/tcp/admin/authentication"
	"example/internal/input/application/websocket"
	authentication3 "example/internal/input/application/websocket/admin/authentication"
	"example/internal/interceptor/facade/admin"
	"example/internal/interceptor/facade/game"
	"example/internal/interceptor/resource"
	"example/internal/middleware/http/admin"
	middleware_admin2 "example/internal/middleware/websocket/admin"
	"example/internal/output/application/cache"
	model2 "example/internal/output/application/cache/model"
	"example/internal/output/application/memory"
	"example/internal/output/application/memory/model"
	mysql2 "example/internal/output/application/mysql"
	mysql3 "example/internal/output/application/mysql/model"
	"example/internal/output/application/producer"
	producer2 "example/internal/output/application/producer/model"
	"example/internal/output/application/resource"
	"example/internal/output/application/resource/model"
	"example/internal/usecase/application/any/admin/authentication"
	any2 "example/internal/usecase/application/any/admin/resource"
	usecase3 "example/internal/usecase/application/any/annoucement"
	usecase2 "example/internal/usecase/application/any/model"
	"example/internal/usecase/application/any/watcher/source"
	any3 "example/internal/usecase/port/any/model"
	"example/pkg"
)

// Injectors from wire.go:

func InitHttpContainer(ctx context.Context) (*HttpContainer, error) {
	response := pkg.NewResponse()
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model)
	abstractHandler := handler.NewAbstractHandler(response, aesHelper, jwtHelper)
	abstractRepository := mysql.NewAbstractRepository(ctx)
	adminUserRepository := resource.NewAdminUserRepository(resourceClient, abstractRepository)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecase.NewAuthenticatorUsecase(adminUserRepository, abstractUsecase)
	authenticatorHandler := controller_admin_authentication.NewAuthenticatorHandler(abstractHandler, authenticatorUsecase)
	abstractMiddleware := middleware_admin.NewAbstractMiddleware(response, rsaHelper, aesHelper)
	adminMiddleware := middleware_admin.NewAdminMiddleware(abstractMiddleware)
	authenticationMiddleware := middleware_admin.NewAuthenticationMiddleware(abstractMiddleware)
	decryptionMiddleware := middleware_admin.NewDecryptionMiddleware(abstractMiddleware)
	encryptionMiddleware := middleware_admin.NewEncryptionMiddleware(abstractMiddleware)
	errorMiddleware := middleware_admin.NewErrorMiddleware(abstractMiddleware)
	loggerMiddleware := middleware_admin.NewLoggerMiddleware(abstractMiddleware)
	nonexistentMiddleware := middleware_admin.NewNonexistentMiddleware(abstractMiddleware)
	requestMiddleware := middleware_admin.NewRequestMiddleware(abstractMiddleware)
	responseMiddleware := middleware_admin.NewResponseMiddleware(abstractMiddleware)
	signatureMiddleware := middleware_admin.NewSignatureMiddleware(abstractMiddleware)
	httpContainer := &HttpContainer{
		Response:                             response,
		AbstractHelper:                       abstractHelper,
		AesHelper:                            aesHelper,
		RsaHelper:                            rsaHelper,
		JwtHelper:                            jwtHelper,
		ResourceClient:                       resourceClient,
		HttpAdminAuthenticationAuthenticator: authenticatorHandler,
		AdminAbstractMiddleware:              abstractMiddleware,
		AdminAdminMiddleware:                 adminMiddleware,
		AdminAuthenticationMiddleware:        authenticationMiddleware,
		AdminDecryptionMiddleware:            decryptionMiddleware,
		AdminEncryptionMiddleware:            encryptionMiddleware,
		AdminErrorMiddleware:                 errorMiddleware,
		AdminLoggerMiddleware:                loggerMiddleware,
		AdminNonexistentMiddleware:           nonexistentMiddleware,
		AdminRequestMiddleware:               requestMiddleware,
		AdminResponseMiddleware:              responseMiddleware,
		AdminSignatureMiddleware:             signatureMiddleware,
	}
	return httpContainer, nil
}

func InitFacadeContainer(ctx context.Context) (*FacadeContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model)
	abstractHandler := facade.NewAbstractHandler(aesHelper)
	scannerHandler := facade2.NewScannerHandler(abstractHandler)
	authenticatorHandler := facade3.NewAuthenticatorHandler(abstractHandler)
	abstractRepository := mysql.NewAbstractRepository(ctx)
	adminUserRepository := resource.NewAdminUserRepository(resourceClient, abstractRepository)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecase.NewAuthenticatorUsecase(adminUserRepository, abstractUsecase)
	authenticationAuthenticatorHandler := authentication.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	abstractInterceptor := interceptor_facade_game.NewAbstractInterceptor(jwtHelper, aesHelper, rsaHelper)
	errorInterceptor := interceptor_facade_game.NewErrorInterceptor(abstractInterceptor)
	statusInterceptor := interceptor_facade_game.NewStatusInterceptor(abstractInterceptor)
	loggerInterceptor := interceptor_facade_game.NewLoggerInterceptor(abstractInterceptor)
	authenticationInterceptor := interceptor_facade_game.NewAuthenticationInterceptor(abstractInterceptor)
	interceptor_facade_adminAbstractInterceptor := interceptor_facade_admin.NewAbstractInterceptor(jwtHelper, aesHelper, rsaHelper)
	interceptor_facade_adminErrorInterceptor := interceptor_facade_admin.NewErrorInterceptor(interceptor_facade_adminAbstractInterceptor)
	interceptor_facade_adminStatusInterceptor := interceptor_facade_admin.NewStatusInterceptor(interceptor_facade_adminAbstractInterceptor)
	interceptor_facade_adminLoggerInterceptor := interceptor_facade_admin.NewLoggerInterceptor(interceptor_facade_adminAbstractInterceptor)
	signatureInterceptor := interceptor_facade_admin.NewSignatureInterceptor(interceptor_facade_adminAbstractInterceptor)
	decryptionInterceptor := interceptor_facade_admin.NewDecryptionInterceptor(interceptor_facade_adminAbstractInterceptor)
	facadeContainer := &FacadeContainer{
		AbstractHelper:                         abstractHelper,
		AesHelper:                              aesHelper,
		RsaHelper:                              rsaHelper,
		JwtHelper:                              jwtHelper,
		ResourceClient:                         resourceClient,
		FacadeAbstract:                         abstractHandler,
		FacadeTableScanner:                     scannerHandler,
		FacadeTableAuthenticator:               authenticatorHandler,
		FacadeAdminAuthenticationAuthenticator: authenticationAuthenticatorHandler,
		FacadeGameErrorInterceptor:             errorInterceptor,
		FacadeGameStatusInterceptor:            statusInterceptor,
		FacadeGameLoggerInterceptor:            loggerInterceptor,
		FacadeGameAuthenticationInterceptor:    authenticationInterceptor,
		FacadeAdminErrorInterceptor:            interceptor_facade_adminErrorInterceptor,
		FacadeAdminStatusInterceptor:           interceptor_facade_adminStatusInterceptor,
		FacadeAdminLoggerInterceptor:           interceptor_facade_adminLoggerInterceptor,
		FacadeAdminSignatureInterceptor:        signatureInterceptor,
		FacadeAdminDecryptionInterceptor:       decryptionInterceptor,
	}
	return facadeContainer, nil
}

func InitResourceContainer(ctx context.Context) (*ResourceContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	abstractUsecase := usecase2.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	aop := pkg.NewAop(ctx, universalClient)
	abstractRepository := mysql2.NewAbstractRepository(ctx, db, aop)
	adminUserRepository := mysql3.NewAdminUserRepository(abstractRepository)
	adminUserUsecase := usecase2.NewAdminUserUsecase(adminUserRepository, abstractUsecase)
	abstractHandler := resource2.NewAbstractHandler()
	adminUserHandler := service.NewAdminUserHandler(abstractHandler, adminUserUsecase)
	abstractInterceptor := interceptor_resource.NewAbstractInterceptor()
	allInterceptor := interceptor_resource.NewAllInterceptor(abstractInterceptor)
	connection, err := bootstrap.NewAmqp()
	if err != nil {
		return nil, err
	}
	producerAbstractRepository, err := producer.NewAbstractRepository(ctx, connection)
	if err != nil {
		return nil, err
	}
	producerAdminUserRepository, err := producer2.NewAdminUserRepository(producerAbstractRepository)
	if err != nil {
		return nil, err
	}
	resourceContainer := &ResourceContainer{
		AbstractHelper:            abstractHelper,
		AesHelper:                 aesHelper,
		RsaHelper:                 rsaHelper,
		AbstractUsecase:           abstractUsecase,
		AdminUserUsecase:          adminUserUsecase,
		ResourceAbstract:          abstractHandler,
		ResourceModelAdminUser:    adminUserHandler,
		ResourceAllInterceptor:    allInterceptor,
		ResourceProducerAdminUser: producerAdminUserRepository,
	}
	return resourceContainer, nil
}

func InitConsumerContainer(ctx context.Context) (*ConsumerContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	connection, err := bootstrap.NewAmqp()
	if err != nil {
		return nil, err
	}
	abstractHandler := consumer.NewAbstractHandler(aesHelper, connection)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	aop := pkg.NewAop(ctx, universalClient)
	abstractRepository := mysql2.NewAbstractRepository(ctx, db, aop)
	appUserRepository := mysql3.NewAppUserRepository(abstractRepository)
	appUserUsecase := any2.NewAppUserUsecase(appUserRepository)
	appUserHandler := consumer2.NewAppUserHandler(appUserUsecase, abstractHandler)
	consumerContainer := &ConsumerContainer{
		AbstractHelper:               abstractHelper,
		AesHelper:                    aesHelper,
		AbstractHandler:              abstractHandler,
		ConsumerAdminResourceAppUser: appUserHandler,
	}
	return consumerContainer, nil
}

func InitCronContainer(ctx context.Context) (*CronContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	aop := pkg.NewAop(ctx, universalClient)
	abstractRepository := mysql2.NewAbstractRepository(ctx, db, aop)
	appUserRepository := mysql3.NewAppUserRepository(abstractRepository)
	appUserUsecase := any2.NewAppUserUsecase(appUserRepository)
	abstractHandler := cron.NewAbstractHandler(aesHelper)
	appUserHandler := cron2.NewAppUserHandler(appUserUsecase, abstractHandler)
	adminUserRepository := mysql3.NewAdminUserRepository(abstractRepository)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecase.NewAuthenticatorUsecase(adminUserRepository, abstractUsecase)
	authenticatorHandler := authentication2.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	cronContainer := &CronContainer{
		AbstractHelper:                       abstractHelper,
		AesHelper:                            aesHelper,
		JwtHelper:                            jwtHelper,
		CronAdminResourceAppUser:             appUserHandler,
		CronAdminAuthenticationAuthenticator: authenticatorHandler,
	}
	return cronContainer, nil
}

func InitWebsocketContainer(ctx context.Context) (*WebsocketContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model)
	abstractHandler := websocket.NewAbstractHandler(aesHelper)
	abstractRepository := mysql.NewAbstractRepository(ctx)
	adminUserRepository := resource.NewAdminUserRepository(resourceClient, abstractRepository)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecase.NewAuthenticatorUsecase(adminUserRepository, abstractUsecase)
	authenticatorHandler := authentication3.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	abstractMiddleware := middleware_admin2.NewAbstractMiddleware(rsaHelper, aesHelper, jwtHelper)
	adminMiddleware := middleware_admin2.NewAdminMiddleware(abstractMiddleware)
	authenticationMiddleware := middleware_admin2.NewAuthenticationMiddleware(abstractMiddleware)
	decryptionMiddleware := middleware_admin2.NewDecryptionMiddleware(abstractMiddleware)
	encryptionMiddleware := middleware_admin2.NewEncryptionMiddleware(abstractMiddleware)
	errorMiddleware := middleware_admin2.NewErrorMiddleware(abstractMiddleware)
	loggerMiddleware := middleware_admin2.NewLoggerMiddleware(abstractMiddleware)
	nonexistentMiddleware := middleware_admin2.NewNonexistentMiddleware(abstractMiddleware)
	requestMiddleware := middleware_admin2.NewRequestMiddleware(abstractMiddleware)
	responseMiddleware := middleware_admin2.NewResponseMiddleware(abstractMiddleware)
	signatureMiddleware := middleware_admin2.NewSignatureMiddleware(abstractMiddleware)
	websocketContainer := &WebsocketContainer{
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		RsaHelper:       rsaHelper,
		JwtHelper:       jwtHelper,
		ResourceClient:  resourceClient,
		AbstractHandler: abstractHandler,
		WebsocketAdminAuthenticationAuthenticator: authenticatorHandler,
		WebsocketAdminAbstractMiddleware:          abstractMiddleware,
		WebsocketAdminAdminMiddleware:             adminMiddleware,
		WebsocketAdminAuthenticationMiddleware:    authenticationMiddleware,
		WebsocketAdminDecryptionMiddleware:        decryptionMiddleware,
		WebsocketAdminEncryptionMiddleware:        encryptionMiddleware,
		WebsocketAdminErrorMiddleware:             errorMiddleware,
		WebsocketAdminLoggerMiddleware:            loggerMiddleware,
		WebsocketAdminNonexistentMiddleware:       nonexistentMiddleware,
		WebsocketAdminRequestMiddleware:           requestMiddleware,
		WebsocketAdminResponseMiddleware:          responseMiddleware,
		WebsocketAdminSignatureMiddleware:         signatureMiddleware,
	}
	return websocketContainer, nil
}

func InitClientContainer() (*ClientContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	clientContainer := &ClientContainer{
		AbstractHelper: abstractHelper,
		AesHelper:      aesHelper,
	}
	return clientContainer, nil
}

func InitCommandContainer(ctx context.Context) (*CommandContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	abstractHandler := command.NewAbstractHandler(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	aop := pkg.NewAop(ctx, universalClient)
	abstractRepository := mysql2.NewAbstractRepository(ctx, db, aop)
	appUserRepository := mysql3.NewAppUserRepository(abstractRepository)
	appUserUsecase := any2.NewAppUserUsecase(appUserRepository)
	appUserHandler := command2.NewAppUserHandler(appUserUsecase, abstractHandler)
	adminUserRepository := mysql3.NewAdminUserRepository(abstractRepository)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecase.NewAuthenticatorUsecase(adminUserRepository, abstractUsecase)
	authenticatorHandler := authentication4.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	commandContainer := &CommandContainer{
		AbstractHelper:                   abstractHelper,
		AesHelper:                        aesHelper,
		JwtHelper:                        jwtHelper,
		AbstractHandler:                  abstractHandler,
		CommandAdminReourceAppUser:       appUserHandler,
		CommandAdminAuthenticationSignIn: authenticatorHandler,
	}
	return commandContainer, nil
}

func InitTcpContainer(ctx context.Context) (*TcpContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model)
	abstractHandler := tcp.NewAbstractHandler(aesHelper)
	abstractRepository := mysql.NewAbstractRepository(ctx)
	adminUserRepository := resource.NewAdminUserRepository(resourceClient, abstractRepository)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecase.NewAuthenticatorUsecase(adminUserRepository, abstractUsecase)
	authenticatorHandler := authentication5.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	tcpContainer := &TcpContainer{
		AbstractHelper:               abstractHelper,
		AesHelper:                    aesHelper,
		JwtHelper:                    jwtHelper,
		ResourceClient:               resourceClient,
		AbstractHandler:              abstractHandler,
		TcpAdminAuthenticationSignIn: authenticatorHandler,
	}
	return tcpContainer, nil
}

func InitSourceContainer(ctx context.Context) (*SourceContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractHandler := resource3.NewAbstractHandler()
	abstractUsecase := usecase3.NewAbstractUsecase(aesHelper)
	abstractRepository := memory.NewAbstractRepository(ctx)
	lotteryRepository := model.NewLotteryRepository(abstractRepository)
	lotteryUsecase := usecase3.NewLotteryUsecase(abstractUsecase, lotteryRepository)
	lotteryHandler := announcement.NewLotteryHandler(abstractHandler, lotteryUsecase)
	sourceContainer := &SourceContainer{
		AbstractHelper:            abstractHelper,
		AesHelper:                 aesHelper,
		SourceAnnouncementLottery: lotteryHandler,
	}
	return sourceContainer, nil
}

func InitDaemonContainer(ctx context.Context) (*DaemonContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	clientConn := bootstrap.NewSource(ctx)
	clientAnnouncement := client.NewAnnouncement(clientConn)
	sourceClient := client.NewSourceClient(clientConn, clientAnnouncement)
	abstractUsecase := source.NewAbstractUsecase(aesHelper)
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	cacheHelper := helper.NewCacheHelper(abstractHelper, universalClient)
	abstractRepository := cache.NewAbstractRepository(ctx, cacheHelper)
	lotteryRepository := model2.NewLotteryRepository(abstractRepository)
	announcementLotteryUsecase := source.NewAnnouncementLotteryUsecase(abstractUsecase, lotteryRepository)
	abstractHandler := daemon.NewAbstractHandler(aesHelper)
	announcementLotteryHandler := source2.NewAnnouncementLotteryHandler(announcementLotteryUsecase, abstractHandler)
	daemonContainer := &DaemonContainer{
		AbstractHelper:                         abstractHelper,
		AesHelper:                              aesHelper,
		SourceClient:                           sourceClient,
		DaemonWatcherSourceAnnouncementLottery: announcementLotteryHandler,
	}
	return daemonContainer, nil
}

// wire.go:

// HttpContainer 只給 `http` Gin 服務使用。
type HttpContainer struct {

	// pkg
	*pkg.Response

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// HTTP server -Controller
	HttpAdminAuthenticationAuthenticator *controller_admin_authentication.AuthenticatorHandler

	// HTTP server -Middleware
	// Middleware 部分
	AdminAbstractMiddleware       *middleware_admin.AbstractMiddleware
	AdminAdminMiddleware          *middleware_admin.AdminMiddleware
	AdminAuthenticationMiddleware *middleware_admin.AuthenticationMiddleware
	AdminDecryptionMiddleware     *middleware_admin.DecryptionMiddleware
	AdminEncryptionMiddleware     *middleware_admin.EncryptionMiddleware
	AdminErrorMiddleware          *middleware_admin.ErrorMiddleware
	AdminLoggerMiddleware         *middleware_admin.LoggerMiddleware
	AdminNonexistentMiddleware    *middleware_admin.NonexistentMiddleware
	AdminRequestMiddleware        *middleware_admin.RequestMiddleware
	AdminResponseMiddleware       *middleware_admin.ResponseMiddleware
	AdminSignatureMiddleware      *middleware_admin.SignatureMiddleware
}

type FacadeContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// gRPC Facade service
	FacadeAbstract                         *facade.AbstractHandler
	FacadeTableScanner                     *facade2.ScannerHandler
	FacadeTableAuthenticator               *facade3.AuthenticatorHandler
	FacadeAdminAuthenticationAuthenticator *authentication.AuthenticatorHandler

	// gRPC Facade Interceptor
	FacadeGameErrorInterceptor          *interceptor_facade_game.ErrorInterceptor
	FacadeGameStatusInterceptor         *interceptor_facade_game.StatusInterceptor
	FacadeGameLoggerInterceptor         *interceptor_facade_game.LoggerInterceptor
	FacadeGameAuthenticationInterceptor *interceptor_facade_game.AuthenticationInterceptor
	FacadeAdminErrorInterceptor         *interceptor_facade_admin.ErrorInterceptor
	FacadeAdminStatusInterceptor        *interceptor_facade_admin.StatusInterceptor
	FacadeAdminLoggerInterceptor        *interceptor_facade_admin.LoggerInterceptor
	FacadeAdminSignatureInterceptor     *interceptor_facade_admin.SignatureInterceptor
	FacadeAdminDecryptionInterceptor    *interceptor_facade_admin.DecryptionInterceptor
}

type ResourceContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper

	*usecase2.AbstractUsecase
	any3.AdminUserUsecase

	// gRPC Resource server
	ResourceAbstract       *resource2.AbstractHandler
	ResourceModelAdminUser *service.AdminUserHandler

	// gRPC Resource Interceptor
	ResourceAllInterceptor *interceptor_resource.AllInterceptor

	// MQ 生產者
	ResourceProducerAdminUser *producer2.AdminUserRepository
}

// ConsumerContainer 只給 `consumer` MQ 消費者服務使用。
type ConsumerContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	// MQ 消費者
	*consumer.AbstractHandler
	ConsumerAdminResourceAppUser *consumer2.AppUserHandler
}

// CronContainer 只給 `cron` 排程服務使用。
type CronContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.JwtHelper

	// 排程 server
	CronAdminResourceAppUser             *cron2.AppUserHandler
	CronAdminAuthenticationAuthenticator *authentication2.AuthenticatorHandler
}

// WebsocketContainer 只給 `websocket` 服務使用。
type WebsocketContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// websocket
	*websocket.AbstractHandler
	WebsocketAdminAuthenticationAuthenticator *authentication3.AuthenticatorHandler

	// Websocket server -Middleware
	WebsocketAdminAbstractMiddleware       *middleware_admin2.AbstractMiddleware
	WebsocketAdminAdminMiddleware          *middleware_admin2.AdminMiddleware
	WebsocketAdminAuthenticationMiddleware *middleware_admin2.AuthenticationMiddleware
	WebsocketAdminDecryptionMiddleware     *middleware_admin2.DecryptionMiddleware
	WebsocketAdminEncryptionMiddleware     *middleware_admin2.EncryptionMiddleware
	WebsocketAdminErrorMiddleware          *middleware_admin2.ErrorMiddleware
	WebsocketAdminLoggerMiddleware         *middleware_admin2.LoggerMiddleware
	WebsocketAdminNonexistentMiddleware    *middleware_admin2.NonexistentMiddleware
	WebsocketAdminRequestMiddleware        *middleware_admin2.RequestMiddleware
	WebsocketAdminResponseMiddleware       *middleware_admin2.ResponseMiddleware
	WebsocketAdminSignatureMiddleware      *middleware_admin2.SignatureMiddleware
}

// ClientContainer 只給 `client` （訂閱外部 gRPC stream）服務使用。
type ClientContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
}

// 、
type CommandContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.JwtHelper

	// command
	*command.AbstractHandler
	CommandAdminReourceAppUser       *command2.AppUserHandler
	CommandAdminAuthenticationSignIn *authentication4.AuthenticatorHandler
}

type TcpContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// tcp
	*tcp.AbstractHandler
	TcpAdminAuthenticationSignIn *authentication5.AuthenticatorHandler
}

type SourceContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	SourceAnnouncementLottery *announcement.LotteryHandler
}

type DaemonContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	// Clients
	SourceClient *client.SourceClient

	DaemonWatcherSourceAnnouncementLottery *source2.AnnouncementLotteryHandler
}
