// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"example/bootstrap"
	"example/internal/client"
	"example/internal/helper"
	"example/internal/input/application/command"
	command2 "example/internal/input/application/command/admin/resource"
	"example/internal/input/application/consumer"
	consumer2 "example/internal/input/application/consumer/admin/resource"
	"example/internal/input/application/cron"
	cron2 "example/internal/input/application/cron/admin/resource"
	"example/internal/input/application/facade"
	facade3 "example/internal/input/application/facade/register"
	facade2 "example/internal/input/application/facade/table"
	"example/internal/input/application/http"
	"example/internal/input/application/http/admin/authentication"
	resource2 "example/internal/input/application/resource"
	"example/internal/input/application/resource/model"
	resource3 "example/internal/input/application/source"
	"example/internal/input/application/source/announcement"
	"example/internal/interceptor/facade/game"
	"example/internal/interceptor/resource"
	"example/internal/middleware/admin"
	"example/internal/output/application/memory/model"
	"example/internal/output/application/mysql/model"
	"example/internal/output/application/resource/model"
	"example/internal/usecase/application/any/admin/authentication"
	any2 "example/internal/usecase/application/any/admin/resource"
	usecase3 "example/internal/usecase/application/any/annoucement"
	usecase2 "example/internal/usecase/application/any/model"
	any3 "example/internal/usecase/port/any/model"
	"example/pkg"
)

// Injectors from wire.go:

func InitHttpContainer() (*HttpContainer, error) {
	response := pkg.NewResponse()
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource()
	model := client.NewModel(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model)
	abstractHandler := handler.NewAbstractHandler(response, aesHelper, jwtHelper)
	adminUserRepository := resource.NewAdminUserRepository(resourceClient)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	authenticatorUsecase := usecase.NewAuthenticatorUsecase(adminUserRepository, abstractUsecase)
	authenticatorHandler := controller_admin_authentication.NewAuthenticatorHandler(abstractHandler, authenticatorUsecase)
	abstractMiddleware := middleware_admin.NewAbstractMiddleware(response, rsaHelper, aesHelper)
	adminMiddleware := middleware_admin.NewAdminMiddleware(abstractMiddleware)
	authenticationMiddleware := middleware_admin.NewAuthenticationMiddleware(abstractMiddleware)
	decryptionMiddleware := middleware_admin.NewDecryptionMiddleware(abstractMiddleware)
	encryptionMiddleware := middleware_admin.NewEncryptionMiddleware(abstractMiddleware)
	errorMiddleware := middleware_admin.NewErrorMiddleware(abstractMiddleware)
	loggerMiddleware := middleware_admin.NewLoggerMiddleware(abstractMiddleware)
	nonexistentMiddleware := middleware_admin.NewNonexistentMiddleware(abstractMiddleware)
	requestMiddleware := middleware_admin.NewRequestMiddleware(abstractMiddleware)
	responseMiddleware := middleware_admin.NewResponseMiddleware(abstractMiddleware)
	signatureMiddleware := middleware_admin.NewSignatureMiddleware(abstractMiddleware)
	httpContainer := &HttpContainer{
		Response:                             response,
		AbstractHelper:                       abstractHelper,
		AesHelper:                            aesHelper,
		RsaHelper:                            rsaHelper,
		JwtHelper:                            jwtHelper,
		ResourceClient:                       resourceClient,
		HttpAdminAuthenticationAuthenticator: authenticatorHandler,
		AdminAbstractMiddleware:              abstractMiddleware,
		AdminAdminMiddleware:                 adminMiddleware,
		AdminAuthenticationMiddleware:        authenticationMiddleware,
		AdminDecryptionMiddleware:            decryptionMiddleware,
		AdminEncryptionMiddleware:            encryptionMiddleware,
		AdminErrorMiddleware:                 errorMiddleware,
		AdminLoggerMiddleware:                loggerMiddleware,
		AdminNonexistentMiddleware:           nonexistentMiddleware,
		AdminRequestMiddleware:               requestMiddleware,
		AdminResponseMiddleware:              responseMiddleware,
		AdminSignatureMiddleware:             signatureMiddleware,
	}
	return httpContainer, nil
}

func InitFacadeContainer() (*FacadeContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	abstractHandler := facade.NewAbstractHandler(aesHelper)
	scannerHandler := facade2.NewScannerHandler(abstractHandler)
	authenticatorHandler := facade3.NewAuthenticatorHandler(abstractHandler)
	abstractInterceptor := interceptor_facade_admin.NewAbstractInterceptor()
	errorInterceptor := interceptor_facade_admin.NewErrorInterceptor(abstractInterceptor)
	statusInterceptor := interceptor_facade_admin.NewStatusInterceptor(abstractInterceptor)
	loggerInterceptor := interceptor_facade_admin.NewLoggerInterceptor(abstractInterceptor)
	authenticationInterceptor := interceptor_facade_admin.NewAuthenticationInterceptor(abstractInterceptor)
	facadeContainer := &FacadeContainer{
		AbstractHelper:                       abstractHelper,
		AesHelper:                            aesHelper,
		RsaHelper:                            rsaHelper,
		FacadeAbstract:                       abstractHandler,
		FacadeTableScanner:                   scannerHandler,
		FacadeTableAuthenticator:             authenticatorHandler,
		FacadeAdminErrorInterceptor:          errorInterceptor,
		FacadeAdminStatusInterceptor:         statusInterceptor,
		FacadeAdminLoggerInterceptor:         loggerInterceptor,
		FacadeAdminAuthenticationInterceptor: authenticationInterceptor,
	}
	return facadeContainer, nil
}

func InitResourceContainer() (*ResourceContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	abstractUsecase := usecase2.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	abstractRepository := mysql.NewAbstractRepository(db)
	adminUserRepository := mysql.NewAdminUserRepository(abstractRepository)
	adminUserUsecase := usecase2.NewAdminUserUsecase(adminUserRepository, abstractUsecase)
	abstractHandler := resource2.NewAbstractHandler()
	adminUserHandler := service.NewAdminUserHandler(abstractHandler, adminUserUsecase)
	abstractInterceptor := interceptor_resource.NewAbstractInterceptor()
	allInterceptor := interceptor_resource.NewAllInterceptor(abstractInterceptor)
	resourceContainer := &ResourceContainer{
		AbstractHelper:         abstractHelper,
		AesHelper:              aesHelper,
		RsaHelper:              rsaHelper,
		AbstractUsecase:        abstractUsecase,
		AdminUserUsecase:       adminUserUsecase,
		ResourceAbstract:       abstractHandler,
		ResourceModelAdminUser: adminUserHandler,
		ResourceAllInterceptor: allInterceptor,
	}
	return resourceContainer, nil
}

func InitConsumerContainer() (*ConsumerContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	connection, err := bootstrap.NewAmqp()
	if err != nil {
		return nil, err
	}
	abstractHandler := consumer.NewAbstractHandler(aesHelper, connection)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	abstractRepository := mysql.NewAbstractRepository(db)
	appUserRepository := mysql.NewAppUserRepository(abstractRepository)
	appUserUsecase := any2.NewAppUserUsecase(appUserRepository)
	appUserHandler := consumer2.NewAppUserHandler(appUserUsecase, abstractHandler)
	consumerContainer := &ConsumerContainer{
		AbstractHelper:               abstractHelper,
		AesHelper:                    aesHelper,
		AbstractHandler:              abstractHandler,
		ConsumerAdminResourceAppUser: appUserHandler,
	}
	return consumerContainer, nil
}

func InitCronContainer() (*CronContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	abstractRepository := mysql.NewAbstractRepository(db)
	appUserRepository := mysql.NewAppUserRepository(abstractRepository)
	appUserUsecase := any2.NewAppUserUsecase(appUserRepository)
	abstractHandler := cron.NewAbstractHandler(aesHelper)
	appUserHandler := cron2.NewAppUserHandler(appUserUsecase, abstractHandler)
	cronContainer := &CronContainer{
		AbstractHelper:           abstractHelper,
		AesHelper:                aesHelper,
		CronAdminResourceAppUser: appUserHandler,
	}
	return cronContainer, nil
}

func InitWebsocketContainer() (*WebsocketContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	websocketContainer := &WebsocketContainer{
		AbstractHelper: abstractHelper,
		AesHelper:      aesHelper,
	}
	return websocketContainer, nil
}

func InitClientContainer() (*ClientContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	clientContainer := &ClientContainer{
		AbstractHelper: abstractHelper,
		AesHelper:      aesHelper,
	}
	return clientContainer, nil
}

func InitCommandContainer() (*CommandContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractHandler := command.NewAbstractHandler(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	abstractRepository := mysql.NewAbstractRepository(db)
	appUserRepository := mysql.NewAppUserRepository(abstractRepository)
	appUserUsecase := any2.NewAppUserUsecase(appUserRepository)
	appUserHandler := command2.NewAppUserHandler(appUserUsecase, abstractHandler)
	commandContainer := &CommandContainer{
		AbstractHelper:             abstractHelper,
		AesHelper:                  aesHelper,
		AbstractHandler:            abstractHandler,
		CommandAdminReourceAppUser: appUserHandler,
	}
	return commandContainer, nil
}

func InitSourceContainer() (*SourceContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractHandler := resource3.NewAbstractHandler()
	abstractUsecase := usecase3.NewAbstractUsecase(aesHelper)
	abstractRepository := model.NewAbstractRepository()
	lotteryRepository := model.NewLotteryRepository(abstractRepository)
	lotteryUsecase := usecase3.NewLotteryUsecase(abstractUsecase, lotteryRepository)
	lotteryHandler := announcement.NewLotteryHandler(abstractHandler, lotteryUsecase)
	sourceContainer := &SourceContainer{
		AbstractHelper:            abstractHelper,
		AesHelper:                 aesHelper,
		SourceAnnouncementLottery: lotteryHandler,
	}
	return sourceContainer, nil
}

func InitDaemonContainer() (*DaemonContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	daemonContainer := &DaemonContainer{
		AbstractHelper: abstractHelper,
		AesHelper:      aesHelper,
	}
	return daemonContainer, nil
}

// wire.go:

// HttpContainer 只給 `http` Gin 服務使用。
type HttpContainer struct {

	// pkg
	*pkg.Response

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// HTTP server -Controller
	HttpAdminAuthenticationAuthenticator *controller_admin_authentication.AuthenticatorHandler

	// HTTP server -Middleware
	// Middleware 部分
	AdminAbstractMiddleware       *middleware_admin.AbstractMiddleware
	AdminAdminMiddleware          *middleware_admin.AdminMiddleware
	AdminAuthenticationMiddleware *middleware_admin.AuthenticationMiddleware
	AdminDecryptionMiddleware     *middleware_admin.DecryptionMiddleware
	AdminEncryptionMiddleware     *middleware_admin.EncryptionMiddleware
	AdminErrorMiddleware          *middleware_admin.ErrorMiddleware
	AdminLoggerMiddleware         *middleware_admin.LoggerMiddleware
	AdminNonexistentMiddleware    *middleware_admin.NonexistentMiddleware
	AdminRequestMiddleware        *middleware_admin.RequestMiddleware
	AdminResponseMiddleware       *middleware_admin.ResponseMiddleware
	AdminSignatureMiddleware      *middleware_admin.SignatureMiddleware
}

type FacadeContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper

	// gRPC Facade server
	FacadeAbstract           *facade.AbstractHandler
	FacadeTableScanner       *facade2.ScannerHandler
	FacadeTableAuthenticator *facade3.AuthenticatorHandler

	// gRPC Facade Interceptor
	FacadeAdminErrorInterceptor          *interceptor_facade_admin.ErrorInterceptor
	FacadeAdminStatusInterceptor         *interceptor_facade_admin.StatusInterceptor
	FacadeAdminLoggerInterceptor         *interceptor_facade_admin.LoggerInterceptor
	FacadeAdminAuthenticationInterceptor *interceptor_facade_admin.AuthenticationInterceptor
}

type ResourceContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper

	*usecase2.AbstractUsecase
	any3.AdminUserUsecase

	// gRPC Resource server
	ResourceAbstract       *resource2.AbstractHandler
	ResourceModelAdminUser *service.AdminUserHandler

	// gRPC Resource Interceptor
	ResourceAllInterceptor *interceptor_resource.AllInterceptor
}

// ConsumerContainer 只給 `consumer` MQ 消費者服務使用。
type ConsumerContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	// MQ 消費者
	*consumer.AbstractHandler
	ConsumerAdminResourceAppUser *consumer2.AppUserHandler
}

// CronContainer 只給 `cron` 排程服務使用。
type CronContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	// 排程 server
	CronAdminResourceAppUser *cron2.AppUserHandler
}

// WebsocketContainer 只給 `websocket` 服務使用。
type WebsocketContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
}

// ClientContainer 只給 `client` （訂閱外部 gRPC stream）服務使用。
type ClientContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
}

// 、
type CommandContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	// command
	*command.AbstractHandler
	CommandAdminReourceAppUser *command2.AppUserHandler
}

type SourceContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	SourceAnnouncementLottery *announcement.LotteryHandler
}

type DaemonContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
}
