// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"example/internal/bootstrap"
	"example/internal/client"
	"example/internal/helper"
	client2 "example/internal/input/client"
	"example/internal/input/consumer"
	"example/internal/input/cron"
	"example/internal/input/facade"
	facade2 "example/internal/input/facade/game"
	facade4 "example/internal/input/facade/register"
	facade3 "example/internal/input/facade/table"
	"example/internal/input/http/admin"
	handler2 "example/internal/input/http/admin/resource"
	"example/internal/input/resource"
	service2 "example/internal/input/resource/model"
	"example/internal/input/websocket"
	"example/internal/middleware/admin"
	"example/internal/output/cache"
	"example/internal/output/mysql"
	"example/internal/usecase"
	"example/internal/usecase/port"
	usecase2 "example/internal/usecase/resource"
	"example/pkg"
)

// Injectors from wire.go:

func InitFacadeContainer() (*FacadeContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	loggerHelper := helper.NewLoggerHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	client, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	cacheHelper := helper.NewCacheHelper(abstractHelper, client)
	userRepository := cache.NewUserRepository(db, cacheHelper)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	abstractHandler := facade.NewAbstractHandler(aesHelper)
	userHandler := facade2.NewUserHandler(userUsecase, abstractHandler)
	scannerHandler := facade3.NewScannerHandler(abstractHandler)
	authenticatorHandler := facade4.NewAuthenticatorHandler(abstractHandler)
	facadeContainer := &FacadeContainer{
		AbstractHelper:           abstractHelper,
		AesHelper:                aesHelper,
		RsaHelper:                rsaHelper,
		LoggerHelper:             loggerHelper,
		AbstractUsecase:          abstractUsecase,
		UserUsecase:              userUsecase,
		FacadeAbstract:           abstractHandler,
		FacadeGameUser:           userHandler,
		FacadeTableScanner:       scannerHandler,
		FacadeTableAuthenticator: authenticatorHandler,
	}
	return facadeContainer, nil
}

func InitResourceContainer() (*ResourceContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	loggerHelper := helper.NewLoggerHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	adminUserRepository := mysql.NewAdminUserRepository(db)
	client, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	cacheHelper := helper.NewCacheHelper(abstractHelper, client)
	userRepository := cache.NewUserRepository(db, cacheHelper)
	usecaseAbstractUsecase := usecase2.NewAbstractUsecase(userRepository, aesHelper)
	adminUserUsecase := usecase2.NewAdminUserUsecase(adminUserRepository, usecaseAbstractUsecase)
	abstractHandler := service.NewAbstractHandler()
	adminUserHandler := service2.NewAdminUserHandler(abstractHandler, adminUserUsecase)
	resourceContainer := &ResourceContainer{
		AbstractHelper:         abstractHelper,
		AesHelper:              aesHelper,
		RsaHelper:              rsaHelper,
		LoggerHelper:           loggerHelper,
		AbstractUsecase:        abstractUsecase,
		AdminUserUsecase:       adminUserUsecase,
		ResourceAbstract:       abstractHandler,
		ResourceModelAdminUser: adminUserHandler,
	}
	return resourceContainer, nil
}

func InitHttpContainer() (*HttpContainer, error) {
	response := pkg.NewResponse()
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	loggerHelper := helper.NewLoggerHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	client, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	cacheHelper := helper.NewCacheHelper(abstractHelper, client)
	userRepository := cache.NewUserRepository(db, cacheHelper)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	abstractHandler := handler.NewAbstractHandler(response, aesHelper)
	userHandler := handler2.NewUserHandler(userUsecase, abstractHandler)
	abstractMiddleware := middleware_admin.NewAbstractMiddleware(response, rsaHelper, aesHelper, loggerHelper)
	adminMiddleware := middleware_admin.NewAdminMiddleware(abstractMiddleware)
	authenticationMiddleware := middleware_admin.NewAuthenticationMiddleware(abstractMiddleware)
	decryptionMiddleware := middleware_admin.NewDecryptionMiddleware(abstractMiddleware)
	encryptionMiddleware := middleware_admin.NewEncryptionMiddleware(abstractMiddleware)
	errorMiddleware := middleware_admin.NewErrorMiddleware(abstractMiddleware)
	loggerMiddleware := middleware_admin.NewLoggerMiddleware(abstractMiddleware)
	nonexistentMiddleware := middleware_admin.NewNonexistentMiddleware(abstractMiddleware)
	requestMiddleware := middleware_admin.NewRequestMiddleware(abstractMiddleware)
	responseMiddleware := middleware_admin.NewResponseMiddleware(abstractMiddleware)
	signatureMiddleware := middleware_admin.NewSignatureMiddleware(abstractMiddleware)
	httpContainer := &HttpContainer{
		Response:                      response,
		AbstractHelper:                abstractHelper,
		AesHelper:                     aesHelper,
		RsaHelper:                     rsaHelper,
		LoggerHelper:                  loggerHelper,
		AbstractUsecase:               abstractUsecase,
		UserUsecase:                   userUsecase,
		HttpAdminResourceUser:         userHandler,
		AdminAbstractMiddleware:       abstractMiddleware,
		AdminAdminMiddleware:          adminMiddleware,
		AdminAuthenticationMiddleware: authenticationMiddleware,
		AdminDecryptionMiddleware:     decryptionMiddleware,
		AdminEncryptionMiddleware:     encryptionMiddleware,
		AdminErrorMiddleware:          errorMiddleware,
		AdminLoggerMiddleware:         loggerMiddleware,
		AdminNonexistentMiddleware:    nonexistentMiddleware,
		AdminRequestMiddleware:        requestMiddleware,
		AdminResponseMiddleware:       responseMiddleware,
		AdminSignatureMiddleware:      signatureMiddleware,
	}
	return httpContainer, nil
}

func InitConsumerContainer() (*ConsumerContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	client, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	cacheHelper := helper.NewCacheHelper(abstractHelper, client)
	userRepository := cache.NewUserRepository(db, cacheHelper)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	connection, err := bootstrap.NewAmqp()
	if err != nil {
		return nil, err
	}
	abstractHandler := consumer.NewAbstractHandler(aesHelper, connection)
	userConsumer, err := consumer.NewUserConsumer(userUsecase, abstractHandler)
	if err != nil {
		return nil, err
	}
	consumerContainer := &ConsumerContainer{
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		AbstractUsecase: abstractUsecase,
		UserUsecase:     userUsecase,
		ConsumerUser:    userConsumer,
	}
	return consumerContainer, nil
}

func InitCronContainer() (*CronContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	client, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	cacheHelper := helper.NewCacheHelper(abstractHelper, client)
	userRepository := cache.NewUserRepository(db, cacheHelper)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	abstractHandler := cron.NewAbstractHandler(aesHelper)
	userCron, err := cron.NewUserCron(userUsecase, abstractHandler)
	if err != nil {
		return nil, err
	}
	cronContainer := &CronContainer{
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		AbstractUsecase: abstractUsecase,
		UserUsecase:     userUsecase,
		CronUser:        userCron,
	}
	return cronContainer, nil
}

func InitContainer() (*Container, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	loggerHelper := helper.NewLoggerHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	redisClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	cacheHelper := helper.NewCacheHelper(abstractHelper, redisClient)
	userRepository := cache.NewUserRepository(db, cacheHelper)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	clientConn, err := bootstrap.NewClient()
	if err != nil {
		return nil, err
	}
	clientClient := client.NewClient(clientConn)
	abstractHandler := client2.NewAbstractHandler(aesHelper, clientClient)
	userHandler := client2.NewUserHandler(userUsecase, abstractHandler)
	facadeAbstractHandler := facade.NewAbstractHandler(aesHelper)
	facadeUserHandler := facade2.NewUserHandler(userUsecase, facadeAbstractHandler)
	scannerHandler := facade3.NewScannerHandler(facadeAbstractHandler)
	websocketAbstractHandler := websocket.NewAbstractHandler(aesHelper)
	websocketUserHandler := websocket.NewUserHandler(userUsecase, websocketAbstractHandler)
	container := &Container{
		AbstractHelper:         abstractHelper,
		AesHelper:              aesHelper,
		RsaHelper:              rsaHelper,
		LoggerHelper:           loggerHelper,
		AbstractUsecase:        abstractUsecase,
		UserUsecase:            userUsecase,
		ClientUser:             userHandler,
		FacadeGameUser:         facadeUserHandler,
		FacadeTableScannerUser: scannerHandler,
		WebsocketUser:          websocketUserHandler,
	}
	return container, nil
}

// wire.go:

type FacadeContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.LoggerHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// gRPC Facade server
	FacadeAbstract           *facade.AbstractHandler
	FacadeGameUser           *facade2.UserHandler
	FacadeTableScanner       *facade3.ScannerHandler
	FacadeTableAuthenticator *facade4.AuthenticatorHandler
}

type ResourceContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.LoggerHelper

	*usecase.AbstractUsecase
	port.AdminUserUsecase

	// gRPC Resource server
	ResourceAbstract       *service.AbstractHandler
	ResourceModelAdminUser *service2.AdminUserHandler
}

// HttpContainer 只給 `http` Gin 服務使用。
type HttpContainer struct {

	// pkg
	*pkg.Response

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.LoggerHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// HTTP server -Controller
	HttpAdminResourceUser *handler2.UserHandler

	// HTTP server -Middleware
	// Middleware 部分
	AdminAbstractMiddleware       *middleware_admin.AbstractMiddleware
	AdminAdminMiddleware          *middleware_admin.AdminMiddleware
	AdminAuthenticationMiddleware *middleware_admin.AuthenticationMiddleware
	AdminDecryptionMiddleware     *middleware_admin.DecryptionMiddleware
	AdminEncryptionMiddleware     *middleware_admin.EncryptionMiddleware
	AdminErrorMiddleware          *middleware_admin.ErrorMiddleware
	AdminLoggerMiddleware         *middleware_admin.LoggerMiddleware
	AdminNonexistentMiddleware    *middleware_admin.NonexistentMiddleware
	AdminRequestMiddleware        *middleware_admin.RequestMiddleware
	AdminResponseMiddleware       *middleware_admin.ResponseMiddleware
	AdminSignatureMiddleware      *middleware_admin.SignatureMiddleware
}

// ConsumerContainer 只給 `consumer` MQ 消費者服務使用。
type ConsumerContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// MQ 消費者
	ConsumerUser *consumer.UserConsumer
}

// CronContainer 只給 `cron` 排程服務使用。
type CronContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// 排程 server
	CronUser *cron.UserCron
}

type Container struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.LoggerHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// gRPC client stream 訂閱
	ClientUser *client2.UserHandler

	// gRPC server
	FacadeGameUser         *facade2.UserHandler
	FacadeTableScannerUser *facade3.ScannerHandler

	// websocket server
	WebsocketUser *websocket.UserHandler
}
