// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"example/bootstrap"
	"example/internal/client"
	"example/internal/helper"
	"example/internal/input/application/command"
	"example/internal/input/application/consumer"
	"example/internal/input/application/cron"
	"example/internal/input/application/facade"
	facade2 "example/internal/input/application/facade/game"
	facade4 "example/internal/input/application/facade/register"
	facade3 "example/internal/input/application/facade/table"
	"example/internal/input/application/http/admin"
	"example/internal/input/application/http/admin/authentication"
	"example/internal/input/application/resource"
	service2 "example/internal/input/application/resource/model"
	"example/internal/input/application/websocket"
	"example/internal/interceptor/facade/game"
	"example/internal/interceptor/resource"
	"example/internal/middleware/admin"
	"example/internal/output/application/mysql/model"
	"example/internal/output/application/resource/model"
	"example/internal/usecase/application/facade/model"
	usecase2 "example/internal/usecase/application/http/admin/authentication"
	usecase3 "example/internal/usecase/application/resource/model"
	"example/internal/usecase/port/facade/model"
	port2 "example/internal/usecase/port/resource/model"
	"example/pkg"
)

// Injectors from wire.go:

func InitHttpContainer() (*HttpContainer, error) {
	response := pkg.NewResponse()
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	userRepository := mysql.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	clientConn := bootstrap.NewResource()
	model := client.NewModel(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model)
	abstractHandler := handler.NewAbstractHandler(response, aesHelper, jwtHelper, resourceClient)
	adminUserRepository := resource.NewAdminUserRepository(resourceClient)
	usecaseAbstractUsecase := usecase2.NewAbstractUsecase(aesHelper)
	authenticatorUsecase := usecase2.NewAuthenticatorUsecase(adminUserRepository, usecaseAbstractUsecase)
	authenticatorHandler := controller_admin_authentication.NewAuthenticatorHandler(abstractHandler, authenticatorUsecase)
	abstractMiddleware := middleware_admin.NewAbstractMiddleware(response, rsaHelper, aesHelper)
	adminMiddleware := middleware_admin.NewAdminMiddleware(abstractMiddleware)
	authenticationMiddleware := middleware_admin.NewAuthenticationMiddleware(abstractMiddleware)
	decryptionMiddleware := middleware_admin.NewDecryptionMiddleware(abstractMiddleware)
	encryptionMiddleware := middleware_admin.NewEncryptionMiddleware(abstractMiddleware)
	errorMiddleware := middleware_admin.NewErrorMiddleware(abstractMiddleware)
	loggerMiddleware := middleware_admin.NewLoggerMiddleware(abstractMiddleware)
	nonexistentMiddleware := middleware_admin.NewNonexistentMiddleware(abstractMiddleware)
	requestMiddleware := middleware_admin.NewRequestMiddleware(abstractMiddleware)
	responseMiddleware := middleware_admin.NewResponseMiddleware(abstractMiddleware)
	signatureMiddleware := middleware_admin.NewSignatureMiddleware(abstractMiddleware)
	httpContainer := &HttpContainer{
		Response:                             response,
		AbstractHelper:                       abstractHelper,
		AesHelper:                            aesHelper,
		RsaHelper:                            rsaHelper,
		JwtHelper:                            jwtHelper,
		AbstractUsecase:                      abstractUsecase,
		UserUsecase:                          userUsecase,
		ResourceClient:                       resourceClient,
		HttpAdminAuthenticationAuthenticator: authenticatorHandler,
		AdminAbstractMiddleware:              abstractMiddleware,
		AdminAdminMiddleware:                 adminMiddleware,
		AdminAuthenticationMiddleware:        authenticationMiddleware,
		AdminDecryptionMiddleware:            decryptionMiddleware,
		AdminEncryptionMiddleware:            encryptionMiddleware,
		AdminErrorMiddleware:                 errorMiddleware,
		AdminLoggerMiddleware:                loggerMiddleware,
		AdminNonexistentMiddleware:           nonexistentMiddleware,
		AdminRequestMiddleware:               requestMiddleware,
		AdminResponseMiddleware:              responseMiddleware,
		AdminSignatureMiddleware:             signatureMiddleware,
	}
	return httpContainer, nil
}

func InitFacadeContainer() (*FacadeContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	userRepository := mysql.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	abstractHandler := facade.NewAbstractHandler(aesHelper)
	userHandler := facade2.NewUserHandler(userUsecase, abstractHandler)
	scannerHandler := facade3.NewScannerHandler(abstractHandler)
	authenticatorHandler := facade4.NewAuthenticatorHandler(abstractHandler)
	abstractInterceptor := interceptor_facade_admin.NewAbstractInterceptor()
	errorInterceptor := interceptor_facade_admin.NewErrorInterceptor(abstractInterceptor)
	statusInterceptor := interceptor_facade_admin.NewStatusInterceptor(abstractInterceptor)
	loggerInterceptor := interceptor_facade_admin.NewLoggerInterceptor(abstractInterceptor)
	authenticationInterceptor := interceptor_facade_admin.NewAuthenticationInterceptor(abstractInterceptor)
	facadeContainer := &FacadeContainer{
		AbstractHelper:                       abstractHelper,
		AesHelper:                            aesHelper,
		RsaHelper:                            rsaHelper,
		AbstractUsecase:                      abstractUsecase,
		UserUsecase:                          userUsecase,
		FacadeAbstract:                       abstractHandler,
		FacadeGameUser:                       userHandler,
		FacadeTableScanner:                   scannerHandler,
		FacadeTableAuthenticator:             authenticatorHandler,
		FacadeAdminErrorInterceptor:          errorInterceptor,
		FacadeAdminStatusInterceptor:         statusInterceptor,
		FacadeAdminLoggerInterceptor:         loggerInterceptor,
		FacadeAdminAuthenticationInterceptor: authenticationInterceptor,
	}
	return facadeContainer, nil
}

func InitResourceContainer() (*ResourceContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	abstractUsecase := usecase3.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	adminUserRepository := mysql.NewAdminUserRepository(db)
	adminUserUsecase := usecase3.NewAdminUserUsecase(adminUserRepository, abstractUsecase)
	abstractHandler := service.NewAbstractHandler()
	adminUserHandler := service2.NewAdminUserHandler(abstractHandler, adminUserUsecase)
	abstractInterceptor := interceptor_resource.NewAbstractInterceptor()
	allInterceptor := interceptor_resource.NewAllInterceptor(abstractInterceptor)
	resourceContainer := &ResourceContainer{
		AbstractHelper:         abstractHelper,
		AesHelper:              aesHelper,
		RsaHelper:              rsaHelper,
		AbstractUsecase:        abstractUsecase,
		AdminUserUsecase:       adminUserUsecase,
		ResourceAbstract:       abstractHandler,
		ResourceModelAdminUser: adminUserHandler,
		ResourceAllInterceptor: allInterceptor,
	}
	return resourceContainer, nil
}

func InitConsumerContainer() (*ConsumerContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	userRepository := mysql.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	connection, err := bootstrap.NewAmqp()
	if err != nil {
		return nil, err
	}
	abstractHandler := consumer.NewAbstractHandler(aesHelper, connection)
	consumerContainer := &ConsumerContainer{
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		AbstractUsecase: abstractUsecase,
		UserUsecase:     userUsecase,
		AbstractHandler: abstractHandler,
	}
	return consumerContainer, nil
}

func InitCronContainer() (*CronContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	userRepository := mysql.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	abstractHandler := cron.NewAbstractHandler(aesHelper)
	userCron, err := cron.NewUserCron(userUsecase, abstractHandler)
	if err != nil {
		return nil, err
	}
	cronContainer := &CronContainer{
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		AbstractUsecase: abstractUsecase,
		UserUsecase:     userUsecase,
		CronUser:        userCron,
	}
	return cronContainer, nil
}

func InitWebsocketContainer() (*WebsocketContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	userRepository := mysql.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	abstractHandler := websocket.NewAbstractHandler(aesHelper)
	userHandler := websocket.NewUserHandler(userUsecase, abstractHandler)
	websocketContainer := &WebsocketContainer{
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		AbstractUsecase: abstractUsecase,
		UserUsecase:     userUsecase,
		WebsocketUser:   userHandler,
	}
	return websocketContainer, nil
}

func InitClientContainer() (*ClientContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	userRepository := mysql.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, abstractUsecase)
	clientContainer := &ClientContainer{
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		AbstractUsecase: abstractUsecase,
		UserUsecase:     userUsecase,
	}
	return clientContainer, nil
}

func InitCommandContainer() (*CommandContainer, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractHandler := command.NewAbstractHandler(aesHelper)
	abstractUsecase := usecase.NewAbstractUsecase(aesHelper)
	commandContainer := &CommandContainer{
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		AbstractHandler: abstractHandler,
		AbstractUsecase: abstractUsecase,
	}
	return commandContainer, nil
}

// wire.go:

// HttpContainer 只給 `http` Gin 服務使用。
type HttpContainer struct {

	// pkg
	*pkg.Response

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// Clients
	ResourceClient *client.ResourceClient

	// HTTP server -Controller
	HttpAdminAuthenticationAuthenticator *controller_admin_authentication.AuthenticatorHandler

	// HTTP server -Middleware
	// Middleware 部分
	AdminAbstractMiddleware       *middleware_admin.AbstractMiddleware
	AdminAdminMiddleware          *middleware_admin.AdminMiddleware
	AdminAuthenticationMiddleware *middleware_admin.AuthenticationMiddleware
	AdminDecryptionMiddleware     *middleware_admin.DecryptionMiddleware
	AdminEncryptionMiddleware     *middleware_admin.EncryptionMiddleware
	AdminErrorMiddleware          *middleware_admin.ErrorMiddleware
	AdminLoggerMiddleware         *middleware_admin.LoggerMiddleware
	AdminNonexistentMiddleware    *middleware_admin.NonexistentMiddleware
	AdminRequestMiddleware        *middleware_admin.RequestMiddleware
	AdminResponseMiddleware       *middleware_admin.ResponseMiddleware
	AdminSignatureMiddleware      *middleware_admin.SignatureMiddleware
}

type FacadeContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// gRPC Facade server
	FacadeAbstract           *facade.AbstractHandler
	FacadeGameUser           *facade2.UserHandler
	FacadeTableScanner       *facade3.ScannerHandler
	FacadeTableAuthenticator *facade4.AuthenticatorHandler

	// gRPC Facade Interceptor
	FacadeAdminErrorInterceptor          *interceptor_facade_admin.ErrorInterceptor
	FacadeAdminStatusInterceptor         *interceptor_facade_admin.StatusInterceptor
	FacadeAdminLoggerInterceptor         *interceptor_facade_admin.LoggerInterceptor
	FacadeAdminAuthenticationInterceptor *interceptor_facade_admin.AuthenticationInterceptor
}

type ResourceContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper

	*usecase3.AbstractUsecase
	port2.AdminUserUsecase

	// gRPC Resource server
	ResourceAbstract       *service.AbstractHandler
	ResourceModelAdminUser *service2.AdminUserHandler

	// gRPC Resource Interceptor
	ResourceAllInterceptor *interceptor_resource.AllInterceptor
}

// ConsumerContainer 只給 `consumer` MQ 消費者服務使用。
type ConsumerContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// MQ 消費者
	*consumer.AbstractHandler
}

// CronContainer 只給 `cron` 排程服務使用。
type CronContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// 排程 server
	CronUser *cron.UserCron
}

// WebsocketContainer 只給 `websocket` 服務使用。
type WebsocketContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	*usecase.AbstractUsecase
	port.UserUsecase

	// websocket server
	WebsocketUser *websocket.UserHandler
}

// ClientContainer 只給 `client` （訂閱外部 gRPC stream）服務使用。
type ClientContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	*usecase.AbstractUsecase
	port.UserUsecase
}

// 、
type CommandContainer struct {

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	// command
	*command.AbstractHandler

	*usecase.AbstractUsecase
}
