// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: resource/model/app_user.proto

package pb_resource_model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppUser_AddAppUser_FullMethodName = "/pb.resource.model.AppUser/AddAppUser"
)

// AppUserClient is the client API for AppUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppUserClient interface {
	AddAppUser(ctx context.Context, in *OneAppUserRequest, opts ...grpc.CallOption) (*OneAppUserResponse, error)
}

type appUserClient struct {
	cc grpc.ClientConnInterface
}

func NewAppUserClient(cc grpc.ClientConnInterface) AppUserClient {
	return &appUserClient{cc}
}

func (c *appUserClient) AddAppUser(ctx context.Context, in *OneAppUserRequest, opts ...grpc.CallOption) (*OneAppUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OneAppUserResponse)
	err := c.cc.Invoke(ctx, AppUser_AddAppUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppUserServer is the server API for AppUser service.
// All implementations must embed UnimplementedAppUserServer
// for forward compatibility.
type AppUserServer interface {
	AddAppUser(context.Context, *OneAppUserRequest) (*OneAppUserResponse, error)
	mustEmbedUnimplementedAppUserServer()
}

// UnimplementedAppUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppUserServer struct{}

func (UnimplementedAppUserServer) AddAppUser(context.Context, *OneAppUserRequest) (*OneAppUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAppUser not implemented")
}
func (UnimplementedAppUserServer) mustEmbedUnimplementedAppUserServer() {}
func (UnimplementedAppUserServer) testEmbeddedByValue()                 {}

// UnsafeAppUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppUserServer will
// result in compilation errors.
type UnsafeAppUserServer interface {
	mustEmbedUnimplementedAppUserServer()
}

func RegisterAppUserServer(s grpc.ServiceRegistrar, srv AppUserServer) {
	// If the following call panics, it indicates UnimplementedAppUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppUser_ServiceDesc, srv)
}

func _AppUser_AddAppUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneAppUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppUserServer).AddAppUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppUser_AddAppUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppUserServer).AddAppUser(ctx, req.(*OneAppUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppUser_ServiceDesc is the grpc.ServiceDesc for AppUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.resource.model.AppUser",
	HandlerType: (*AppUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAppUser",
			Handler:    _AppUser_AddAppUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/model/app_user.proto",
}
