// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: resource/logic/app_user.proto

package pb_resource_logic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneAppUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneAppUserRequest) Reset() {
	*x = OneAppUserRequest{}
	mi := &file_resource_logic_app_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneAppUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneAppUserRequest) ProtoMessage() {}

func (x *OneAppUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_app_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneAppUserRequest.ProtoReflect.Descriptor instead.
func (*OneAppUserRequest) Descriptor() ([]byte, []int) {
	return file_resource_logic_app_user_proto_rawDescGZIP(), []int{0}
}

func (x *OneAppUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OneAppUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneAppUserResponse) Reset() {
	*x = OneAppUserResponse{}
	mi := &file_resource_logic_app_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneAppUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneAppUserResponse) ProtoMessage() {}

func (x *OneAppUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_app_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneAppUserResponse.ProtoReflect.Descriptor instead.
func (*OneAppUserResponse) Descriptor() ([]byte, []int) {
	return file_resource_logic_app_user_proto_rawDescGZIP(), []int{1}
}

func (x *OneAppUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_resource_logic_app_user_proto protoreflect.FileDescriptor

const file_resource_logic_app_user_proto_rawDesc = "" +
	"\n" +
	"\x1dresource/logic/app_user.proto\x12\x11pb.resource.logic\"'\n" +
	"\x11OneAppUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x12OneAppUserResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2d\n" +
	"\aAppUser\x12Y\n" +
	"\n" +
	"AddAppUser\x12$.pb.resource.logic.OneAppUserRequest\x1a%.pb.resource.logic.OneAppUserResponseB\x15Z\x13./pb_resource_logicb\x06proto3"

var (
	file_resource_logic_app_user_proto_rawDescOnce sync.Once
	file_resource_logic_app_user_proto_rawDescData []byte
)

func file_resource_logic_app_user_proto_rawDescGZIP() []byte {
	file_resource_logic_app_user_proto_rawDescOnce.Do(func() {
		file_resource_logic_app_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_logic_app_user_proto_rawDesc), len(file_resource_logic_app_user_proto_rawDesc)))
	})
	return file_resource_logic_app_user_proto_rawDescData
}

var file_resource_logic_app_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_logic_app_user_proto_goTypes = []any{
	(*OneAppUserRequest)(nil),  // 0: pb.resource.logic.OneAppUserRequest
	(*OneAppUserResponse)(nil), // 1: pb.resource.logic.OneAppUserResponse
}
var file_resource_logic_app_user_proto_depIdxs = []int32{
	0, // 0: pb.resource.logic.AppUser.AddAppUser:input_type -> pb.resource.logic.OneAppUserRequest
	1, // 1: pb.resource.logic.AppUser.AddAppUser:output_type -> pb.resource.logic.OneAppUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_logic_app_user_proto_init() }
func file_resource_logic_app_user_proto_init() {
	if File_resource_logic_app_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_logic_app_user_proto_rawDesc), len(file_resource_logic_app_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_logic_app_user_proto_goTypes,
		DependencyIndexes: file_resource_logic_app_user_proto_depIdxs,
		MessageInfos:      file_resource_logic_app_user_proto_msgTypes,
	}.Build()
	File_resource_logic_app_user_proto = out.File
	file_resource_logic_app_user_proto_goTypes = nil
	file_resource_logic_app_user_proto_depIdxs = nil
}
