// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: source/announcement/lottery.proto

package pb_source_announcement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lottery_Watch_FullMethodName = "/pb.source.announcement.Lottery/Watch"
)

// LotteryClient is the client API for Lottery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotteryClient interface {
	Watch(ctx context.Context, in *LotteryWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LotteryWatchReply], error)
}

type lotteryClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryClient(cc grpc.ClientConnInterface) LotteryClient {
	return &lotteryClient{cc}
}

func (c *lotteryClient) Watch(ctx context.Context, in *LotteryWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LotteryWatchReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Lottery_ServiceDesc.Streams[0], Lottery_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LotteryWatchRequest, LotteryWatchReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Lottery_WatchClient = grpc.ServerStreamingClient[LotteryWatchReply]

// LotteryServer is the server API for Lottery service.
// All implementations must embed UnimplementedLotteryServer
// for forward compatibility.
type LotteryServer interface {
	Watch(*LotteryWatchRequest, grpc.ServerStreamingServer[LotteryWatchReply]) error
	mustEmbedUnimplementedLotteryServer()
}

// UnimplementedLotteryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotteryServer struct{}

func (UnimplementedLotteryServer) Watch(*LotteryWatchRequest, grpc.ServerStreamingServer[LotteryWatchReply]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedLotteryServer) mustEmbedUnimplementedLotteryServer() {}
func (UnimplementedLotteryServer) testEmbeddedByValue()                 {}

// UnsafeLotteryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryServer will
// result in compilation errors.
type UnsafeLotteryServer interface {
	mustEmbedUnimplementedLotteryServer()
}

func RegisterLotteryServer(s grpc.ServiceRegistrar, srv LotteryServer) {
	// If the following call panics, it indicates UnimplementedLotteryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lottery_ServiceDesc, srv)
}

func _Lottery_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LotteryWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LotteryServer).Watch(m, &grpc.GenericServerStream[LotteryWatchRequest, LotteryWatchReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Lottery_WatchServer = grpc.ServerStreamingServer[LotteryWatchReply]

// Lottery_ServiceDesc is the grpc.ServiceDesc for Lottery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lottery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.source.announcement.Lottery",
	HandlerType: (*LotteryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Lottery_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "source/announcement/lottery.proto",
}
